name: Frontend Deployment 👀
on: [push]
jobs:

  build:
    name: 🔥 New Update Gang Gang
    runs-on: ubuntu-latest
    steps:
    - name: Deploying frontend - latest commit
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami